'use client';
import { useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { getBff, postBff } from '@/lib/api';
import { ImportSourceStatus } from '@/components/imports/ImportSourceStatus';
import { ImportItemList } from '@/components/imports/ImportItemList';
import { ImportReviewDialog } from '@/components/imports/ImportReviewDialog';
import { toNoticeRequest } from '@/lib/notice/logic';
import type { ImportedItem, ImportPage, ImportRunStatus, ImportSource, ImportStatus } from '@/lib/imports/types';
import type { Me } from '@/lib/feed/types';
import { Button } from '@/components/ui/Button';
import { StatusMessage } from '@/components/ui/StatusMessage';
export default function AdminImportsPage() {
  const router = useRouter(); const [status, setStatus] = useState<ImportStatus>('NEW'); const [source, setSource] = useState<ImportSource | ''>(''); const [page, setPage] = useState(0); const [items, setItems] = useState<ImportedItem[]>([]); const [runs, setRuns] = useState<ImportRunStatus[]>([]); const [review, setReview] = useState<ImportedItem | null>(null); const [pending, setPending] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { const q = new URLSearchParams({ status, page: String(page), size: '50' }); if (source) q.set('source', source); const r = await getBff<ImportPage>(`/api/bff/admin/imports?${q}`); if (r.ok) setItems((r.data as ImportPage).content); else setError(r.message ?? '목록을 불러오지 못했습니다.'); setLoading(false); }, [status, source, page]);
  const loadRuns = useCallback(async () => { const r = await getBff<ImportRunStatus[]>('/api/bff/admin/imports/runs/latest'); if (r.ok) setRuns(r.data as ImportRunStatus[]); }, []);
  useEffect(() => { getBff<Me>('/api/bff/me/identity').then((r) => { if (!r.ok) router.push('/login'); else if ((r.data as Me).role !== 'ADMIN') router.push('/'); else { void load(); void loadRuns(); } }); }, [router, load, loadRuns]);
  useEffect(() => { const running = runs.some((r) => !r.finishedAt); if (!running) return undefined; const timer = window.setInterval(() => { void loadRuns(); }, 5000); return () => window.clearInterval(timer); }, [runs, loadRuns]);
  async function run(s: ImportSource) { setPending(true); const r = await postBff(`/api/bff/admin/imports/runs?source=${s}`); setPending(false); if (!r.ok) setError(r.message ?? '실행하지 못했습니다.'); else void loadRuns(); }
  async function approve(values: Parameters<NonNullable<React.ComponentProps<typeof ImportReviewDialog>['onSubmit']>>[0]) { if (!review) return; setPending(true); const r = await postBff(`/api/bff/admin/imports/${review.id}/approve`, { notice: toNoticeRequest(values) }); setPending(false); if (r.ok) { setReview(null); void load(); } else setError(r.message ?? '승인하지 못했습니다.'); }
  async function reject(item: ImportedItem) { if (!window.confirm(`"${item.title}" 항목을 거절할까요?`)) return; const r = await postBff(`/api/bff/admin/imports/${item.id}/reject`); if (r.ok) void load(); else setError(r.message ?? '거절하지 못했습니다.'); }
  if (review) return <ImportReviewDialog item={review} pending={pending} onSubmit={approve} onCancel={() => setReview(null)} />;
  return <main className="mx-auto mt-8 max-w-4xl px-4 pb-12"><div className="mb-5 flex items-center justify-between"><h1 className="text-2xl font-bold">외부 반입 심사</h1><a href="/admin/notices" className="text-sm text-ink-muted">공지 관리</a></div>{error && <StatusMessage tone="danger">{error}</StatusMessage>}<div className="border-y border-line">{(['KOPIS', 'UNIV_NOTICE'] as ImportSource[]).map((s) => <ImportSourceStatus key={s} source={s} run={runs.find((r) => r.source === s)} pending={pending} onRun={() => run(s)} />)}</div><div className="mt-6 flex flex-wrap gap-2">{(['NEW', 'APPROVED', 'REJECTED'] as ImportStatus[]).map((s) => <Button type="button" key={s} variant={status === s ? 'primary' : 'secondary'} onClick={() => { setStatus(s); setPage(0); }}>{s === 'NEW' ? '새 항목' : s === 'APPROVED' ? '승인됨' : '거절됨'}</Button>)}<select aria-label="원천 필터" value={source} onChange={(e) => { setSource(e.target.value as ImportSource | ''); setPage(0); }} className="rounded border border-line px-2 py-1.5 text-sm"><option value="">전체 원천</option><option value="KOPIS">KOPIS</option><option value="UNIV_NOTICE">대학 공지</option></select></div>{loading ? <p className="py-8 text-center">불러오는 중...</p> : <ImportItemList items={items} onApprove={setReview} onReject={reject} />}<div className="mt-5 flex justify-center gap-4"><Button type="button" variant="secondary" disabled={page === 0} onClick={() => setPage((p) => p - 1)}>이전</Button><span>{page + 1}</span><Button type="button" variant="secondary" disabled={items.length < 50} onClick={() => setPage((p) => p + 1)}>다음</Button></div></main>;
}
